name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt

      - name: Run unit-tests
        run: |
          .\venv\Scripts\activate
          pytest -q